using RSELFANG.Models;
using SevenFramework.DataBase;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace RSELFANG.DAO
{
    public class DAOSoCoxcn
    {
        public List<TOSoCocxn> getsocoxcn(string soc_codi, int emp_codi, DateTime cox_fech)
        {
            var db = new DbConnection();
            StringBuilder sql = new StringBuilder();
            if (db._provider == "System.Data.SqlClient")
            {
                sql.Append("SELECT SO_COXCN.COX_AINI,                                                                       ");
                sql.Append("SO_COXCN.COX_MINI,                                                                              ");
                sql.Append("SO_COXCN.COX_AFIN,                                                                              ");
                sql.Append("SO_COXCN.COX_MFIN, SO_COXCN.CON_CONT    ,                                                        ");
                sql.Append("SO_DCOXC.DCO_PLAC,                                                                              ");
                sql.Append("SO_SBENE.SBE_NOMB + ' ' + SO_SBENE.SBE_APEL 'SBE_NOMB',                                         ");
                sql.Append("IN_PRODU.PRO_CODI,                                                                              ");
                sql.Append("IN_PRODU.PRO_NOMB,                                                                              ");
                sql.Append("CASE SO_DCOXC.DCO_TOMV                                                                          ");
                sql.Append("WHEN 'N' THEN SO_DCOXC.DCO_VALO                                                                 ");
                sql.Append("ELSE(                                                                                           ");
                sql.Append("SELECT TOP(1) FA_DLIST.DLI_VALO                                                                        ");
                sql.Append("FROM   FA_DLIST                                                                                 ");
                sql.Append("WHERE  LIS_CODI = SO_COXCN.LIS_CODI                                                             ");
                sql.Append("AND PRO_CONT = SO_DCOXC.PRO_CONT                                                                ");
                sql.Append("AND ITE_CACC = (                                                                                ");
                sql.Append("SELECT FA_DCLIE.DCL_ICAC                                                                        ");
                sql.Append("FROM   FA_CLIEN                                                                                 ");
                sql.Append("INNER JOIN FA_DCLIE                                                                             ");
                sql.Append("ON  FA_CLIEN.EMP_CODI = FA_DCLIE.EMP_CODI                                                       ");
                sql.Append("AND FA_CLIEN.CLI_CODI = FA_DCLIE.CLI_CODI                                                       ");
                sql.Append("INNER JOIN GN_TERCE                                                                             ");
                sql.Append("ON  GN_TERCE.EMP_CODI = FA_CLIEN.EMP_CODI                                                       ");
                sql.Append("AND GN_TERCE.TER_CODI = FA_CLIEN.TER_CODI                                                       ");
                sql.Append("WHERE  GN_TERCE.TER_CODA = @SOC_CODI                                                            ");
                sql.Append("AND FA_CLIEN.EMP_CODI = @EMP_CODI                                                               ");
                sql.Append("AND FA_DCLIE.DCL_CODD = 1                                                                       ");
                sql.Append(")                                                                                               ");
                sql.Append(")                                                                                               ");
                sql.Append("END AS 'PRO_VALO',                                                                              ");
                sql.Append("CASE(                                                                                           ");
                sql.Append("SELECT COUNT(*)                                                                                 ");
                sql.Append("FROM   SO_DTACR                                                                                 ");
                sql.Append("INNER JOIN SO_TACRE                                                                             ");
                sql.Append("ON  SO_TACRE.EMP_CODI = SO_DTACR.EMP_CODI                                                       ");
                sql.Append("AND SO_TACRE.SOC_CONT = SO_DTACR.SOC_CONT                                                       ");
                sql.Append("INNER JOIN SO_SOCIO                                                                             ");
                sql.Append("ON  SO_TACRE.EMP_CODI = SO_SOCIO.EMP_CODI                                                       ");
                sql.Append("AND SO_SOCIO.SOC_CONT = SO_TACRE.SOC_CONT                                                       ");
                sql.Append("WHERE  PRO_CONT = SO_DCOXC.PRO_CONT                                                             ");
                sql.Append("AND SO_TACRE.EMP_CODI = @EMP_CODI                                                               ");
                sql.Append("AND SO_SOCIO.SOC_CODI = @SOC_CODI                                                               ");
                sql.Append("AND SO_DTACR.SBE_CONT = SO_SBENE.SBE_CONT                                                       ");
                sql.Append(")                                                                                               ");
                sql.Append("WHEN 0 THEN 'EFECTIVO'                                                                          ");
                sql.Append("ELSE(                                                                                           ");
                sql.Append("SELECT TOP(1) SO_TACRE.TAC_TITA + '-' + SO_TACRE.TAC_NUTA                                       ");
                sql.Append("FROM   SO_DTACR                                                                                 ");
                sql.Append("INNER JOIN SO_TACRE                                                                             ");
                sql.Append("ON  SO_TACRE.EMP_CODI = SO_DTACR.EMP_CODI                                                       ");
                sql.Append("AND SO_TACRE.SOC_CONT = SO_DTACR.SOC_CONT                                                       ");
                sql.Append("INNER JOIN SO_SOCIO                                                                             ");
                sql.Append("ON  SO_TACRE.EMP_CODI = SO_SOCIO.EMP_CODI                                                       ");
                sql.Append("AND SO_SOCIO.SOC_CONT = SO_TACRE.SOC_CONT                                                       ");
                sql.Append("WHERE  PRO_CONT = SO_DCOXC.PRO_CONT                                                             ");
                sql.Append("AND SO_TACRE.EMP_CODI = @EMP_CODI                                                               ");
                sql.Append("AND SO_SOCIO.SOC_CODI = @SOC_CODI                                                               ");
                sql.Append("AND SO_DTACR.SBE_CONT = SO_SBENE.SBE_CONT                                                       ");
                sql.Append(")                                                                                               ");
                sql.Append("END AS 'PRO_FPAG'                                                                               ");
                sql.Append("FROM SO_COXCN                                                                                   ");
                sql.Append("INNER JOIN SO_DCOXC                                                                             ");
                sql.Append("ON  SO_COXCN.EMP_CODI = SO_DCOXC.EMP_CODI                                                       ");
                sql.Append("AND SO_COXCN.COX_CONT = SO_DCOXC.COX_CONT                                                       ");
                sql.Append("JOIN SO_SBENE                                                                                   ");
                sql.Append("ON SO_DCOXC.EMP_CODI = SO_SBENE.EMP_CODI                                                        ");
                sql.Append("AND SO_DCOXC.SOC_CONT = SO_SBENE.SOC_CONT                                                       ");
                sql.Append("AND SO_DCOXC.MAC_NUME = SO_SBENE.MAC_NUME                                                       ");
                sql.Append("AND SO_DCOXC.SBE_CONT = SO_SBENE.SBE_CONT                                                       ");
                sql.Append("INNER JOIN SO_SOCIO                                                                             ");
                sql.Append("ON  SO_SOCIO.EMP_CODI = SO_COXCN.EMP_CODI                                                       ");
                sql.Append("AND SO_SOCIO.SOC_CONT = SO_COXCN.SOC_CONT                                                       ");
                sql.Append("INNER JOIN IN_PRODU                                                                             ");
                sql.Append("ON  SO_DCOXC.EMP_CODI = IN_PRODU.EMP_CODI                                                       ");
                sql.Append("AND SO_DCOXC.PRO_CONT = IN_PRODU.PRO_CONT                                                       ");
                sql.Append("WHERE SO_DCOXC.EMP_CODI = @EMP_CODI                                                             ");
                //sql.Append("AND SO_COXCN.COX_FECH >= @COX_FECH                                                              ");
                sql.Append("AND SO_SOCIO.SOC_CODI = @SOC_CODI                                                               ");
                sql.Append("AND SO_COXCN.COX_ESTA IN('V','R')                                                               ");
            }
            else
            {
                sql.Append("SELECT SO_COXCN.COX_AINI,                                       ");
                sql.Append("SO_COXCN.COX_MINI,                                              ");
                sql.Append("SO_COXCN.COX_AFIN,                                              ");
                sql.Append("SO_COXCN.COX_MFIN,                                              ");
                sql.Append("SO_COXCN.CON_CONT,                                              ");
                sql.Append("SO_DCOXC.DCO_PLAC,                                              ");
                sql.Append("SO_SBENE.SBE_NOMB || ' ' || SO_SBENE.SBE_APEL SBE_NOMB,         ");
                sql.Append("IN_PRODU.PRO_CODI,                                              ");
                sql.Append("IN_PRODU.PRO_NOMB,                                              ");
                sql.Append("CASE SO_DCOXC.DCO_TOMV                                          ");
                sql.Append("WHEN 'N' THEN SO_DCOXC.DCO_VALO                                 ");
                sql.Append("ELSE(                                                           ");
                sql.Append("SELECT FA_DLIST.DLI_VALO                                        ");
                sql.Append("FROM   FA_DLIST                                                 ");
                sql.Append("WHERE  LIS_CODI = SO_COXCN.LIS_CODI                             ");
                sql.Append("AND PRO_CONT = SO_DCOXC.PRO_CONT                                ");
                sql.Append("AND ROWNUM=1                                                    ");
                sql.Append("AND ITE_CACC = (                                                ");
                sql.Append("SELECT FA_DCLIE.DCL_ICAC                                        ");
                sql.Append("FROM   FA_CLIEN                                                 ");
                sql.Append("INNER JOIN FA_DCLIE                                             ");
                sql.Append("ON  FA_CLIEN.EMP_CODI = FA_DCLIE.EMP_CODI                       ");
                sql.Append("AND FA_CLIEN.CLI_CODI = FA_DCLIE.CLI_CODI                       ");
                sql.Append("INNER JOIN GN_TERCE                                             ");
                sql.Append("ON  GN_TERCE.EMP_CODI = FA_CLIEN.EMP_CODI                       ");
                sql.Append("AND GN_TERCE.TER_CODI = FA_CLIEN.TER_CODI                       ");
                sql.Append("WHERE  GN_TERCE.TER_CODA = @SOC_CODI                            ");
                sql.Append("AND FA_CLIEN.EMP_CODI = @EMP_CODI                               ");
                sql.Append("AND FA_DCLIE.DCL_CODD = 1                                       ");
                sql.Append(")                                                               ");
                sql.Append(")                                                               ");
                sql.Append("END PRO_VALO,                                                   ");
                sql.Append("CASE TO_CHAR((                                                  ");
                sql.Append("SELECT COUNT(*)                                                 ");
                sql.Append("FROM   SO_DTACR                                                 ");
                sql.Append("INNER JOIN SO_TACRE                                             ");
                sql.Append("ON  SO_TACRE.EMP_CODI = SO_DTACR.EMP_CODI                       ");
                sql.Append("AND SO_TACRE.SOC_CONT = SO_DTACR.SOC_CONT                       ");
                sql.Append("INNER JOIN SO_SOCIO                                             ");
                sql.Append("ON  SO_TACRE.EMP_CODI = SO_SOCIO.EMP_CODI                       ");
                sql.Append("AND SO_SOCIO.SOC_CONT = SO_TACRE.SOC_CONT                       ");
                sql.Append("WHERE  PRO_CONT = SO_DCOXC.PRO_CONT                             ");
                sql.Append("AND SO_TACRE.EMP_CODI = 1                                       ");
                sql.Append("AND SO_SOCIO.SOC_CODI = @SOC_CODI                               ");
                sql.Append("AND SO_DTACR.SBE_CONT = SO_SBENE.SBE_CONT                       ");
                sql.Append("))                                                              ");
                sql.Append("WHEN '0' THEN 'EFECTIVO'                                        ");
                sql.Append("ELSE(                                                           ");
                sql.Append("SELECT SO_TACRE.TAC_TITA || '-' || SO_TACRE.TAC_NUTA            ");
                sql.Append("FROM   SO_DTACR                                                 ");
                sql.Append("INNER JOIN SO_TACRE                                             ");
                sql.Append("ON  SO_TACRE.EMP_CODI = SO_DTACR.EMP_CODI                       ");
                sql.Append("AND SO_TACRE.SOC_CONT = SO_DTACR.SOC_CONT                       ");
                sql.Append("INNER JOIN SO_SOCIO                                             ");
                sql.Append("ON  SO_TACRE.EMP_CODI = SO_SOCIO.EMP_CODI                       ");
                sql.Append("AND SO_SOCIO.SOC_CONT = SO_TACRE.SOC_CONT                       ");
                sql.Append("WHERE  PRO_CONT = SO_DCOXC.PRO_CONT                             ");
                sql.Append("AND SO_TACRE.EMP_CODI = @EMP_CODI                               ");
                sql.Append("AND SO_SOCIO.SOC_CODI = @SOC_CODI                               ");
                sql.Append("AND SO_DTACR.SBE_CONT = SO_SBENE.SBE_CONT AND ROWNUM = 1        ");
                sql.Append(")                                                               ");
                sql.Append("END PRO_FPAG                                                    ");
                sql.Append("FROM SO_COXCN                                                   ");
                sql.Append("INNER JOIN SO_DCOXC                                             ");
                sql.Append("ON  SO_COXCN.EMP_CODI = SO_DCOXC.EMP_CODI                       ");
                sql.Append("AND SO_COXCN.COX_CONT = SO_DCOXC.COX_CONT                       ");
                sql.Append("JOIN SO_SBENE                                                   ");
                sql.Append("ON SO_DCOXC.EMP_CODI = SO_SBENE.EMP_CODI                        ");
                sql.Append("AND SO_DCOXC.SOC_CONT = SO_SBENE.SOC_CONT                       ");
                sql.Append("AND SO_DCOXC.MAC_NUME = SO_SBENE.MAC_NUME                       ");
                sql.Append("AND SO_DCOXC.SBE_CONT = SO_SBENE.SBE_CONT                       ");
                sql.Append("INNER JOIN SO_SOCIO                                             ");
                sql.Append("ON  SO_SOCIO.EMP_CODI = SO_COXCN.EMP_CODI                       ");
                sql.Append("AND SO_SOCIO.SOC_CONT = SO_COXCN.SOC_CONT                       ");
                sql.Append("INNER JOIN IN_PRODU                                             ");
                sql.Append("ON  SO_DCOXC.EMP_CODI = IN_PRODU.EMP_CODI                       ");
                sql.Append("AND SO_DCOXC.PRO_CONT = IN_PRODU.PRO_CONT                       ");
                sql.Append("WHERE SO_DCOXC.EMP_CODI = @EMP_CODI                             ");
                sql.Append("AND SO_SOCIO.SOC_CODI = @SOC_CODI                               ");
                sql.Append("AND SO_COXCN.COX_ESTA IN('V', 'R')                              ");
            }
            List<SQLParams> sqlParam = new List<SQLParams>();
            sqlParam.Add(new SQLParams("emp_codi", emp_codi));
            sqlParam.Add(new SQLParams("soc_codi", soc_codi));          
            return db.GetList<TOSoCocxn>(sql.ToString(), sqlParam);
        }
    }
}